version: '3.7'

services:
  app-frontend-charging:
    container_name: frontend-charging
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    ports:
      - 3001:3001
